# Generated by Django 3.0.10 on 2020-09-10 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseTaxonomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='name')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='slug')),
                ('value', models.FloatField(default=0, max_length=200, verbose_name='value')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('basetaxonomy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='taxonomies.BaseTaxonomy')),
                ('hex', models.CharField(max_length=6, null=True, verbose_name='hex')),
            ],
            bases=('taxonomies.basetaxonomy',),
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('basetaxonomy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='taxonomies.BaseTaxonomy')),
            ],
            options={
                'verbose_name_plural': 'countries',
            },
            bases=('taxonomies.basetaxonomy',),
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('basetaxonomy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='taxonomies.BaseTaxonomy')),
                ('order', models.IntegerField(blank=True, verbose_name='order')),
            ],
            bases=('taxonomies.basetaxonomy',),
        ),
        migrations.CreateModel(
            name='TargetGroup',
            fields=[
                ('basetaxonomy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='taxonomies.BaseTaxonomy')),
            ],
            options={
                'verbose_name': 'target group',
            },
            bases=('taxonomies.basetaxonomy',),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='name')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='slug')),
                ('value', models.FloatField(default=0, max_length=200, verbose_name='value')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='taxonomies.Category', verbose_name='parent')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'unique_together': {('slug', 'parent')},
            },
        ),
    ]
