# Generated by Django 3.0.10 on 2020-10-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='countries',
            field=models.ManyToManyField(null=True, related_name='currency', to='taxonomies.Country', verbose_name='countries'),
        ),
    ]
