# Generated by Django 3.0.10 on 2020-10-07 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20201007_1104'),
        ('taxonomies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaDataCurrency',
            fields=[
                ('basicmetadata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.BasicMetaData')),
                ('taxonomy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta_data', to='taxonomies.Currency', verbose_name='taxonomy')),
            ],
            bases=('shop.basicmetadata',),
        ),
        migrations.CreateModel(
            name='MetaDataCountry',
            fields=[
                ('basicmetadata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.BasicMetaData')),
                ('taxonomy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta_data', to='taxonomies.Country', verbose_name='taxonomy')),
            ],
            bases=('shop.basicmetadata',),
        ),
        migrations.CreateModel(
            name='MetaDataCompanyType',
            fields=[
                ('basicmetadata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.BasicMetaData')),
                ('taxonomy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta_data', to='taxonomies.CompanyType', verbose_name='taxonomy')),
            ],
            bases=('shop.basicmetadata',),
        ),
    ]
