# Generated by Django 3.0.10 on 2020-09-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomies', '0002_auto_20200909_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basetaxonomy',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='slug'),
        ),
    ]
