# Generated by Django 3.0.10 on 2020-10-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomies', '0003_auto_20201002_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='countries',
            field=models.ManyToManyField(blank=True, related_name='currency', to='taxonomies.Country', verbose_name='countries'),
        ),
    ]
