# Generated by Django 3.0.10 on 2020-10-03 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logs', '0001_initial'),
        ('shop', '0001_initial'),
        ('users', '0001_initial'),
        ('taxonomies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymoususerdata',
            name='body_measurements',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.BodyMeasurements', verbose_name='body measurements'),
        ),
        migrations.AddField(
            model_name='taxonomyvaluelog',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taxonomies.Category', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='taxonomyvaluelog',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taxonomies.Color', verbose_name='color'),
        ),
        migrations.AddField(
            model_name='taxonomyvaluelog',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taxonomies.Size', verbose_name='size'),
        ),
        migrations.AddField(
            model_name='productvaluelog',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Product', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='productvaluelog',
            name='product_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.ProductManager', verbose_name='product manager'),
        ),
        migrations.AddField(
            model_name='productvaluelog',
            name='product_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.ProductOption', verbose_name='product option'),
        ),
        migrations.AddField(
            model_name='brandvaluelog',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Brand', verbose_name='brand'),
        ),
    ]
