# Generated by Django 3.0.10 on 2020-09-10 11:26

from django.db import migrations, models
import django.db.models.deletion
import shop.models.brand
import shop.models.media


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomies', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, verbose_name='order')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='name')),
                ('logo', models.ImageField(blank=True, upload_to=shop.models.brand.create_upload_path, verbose_name='logo')),
                ('value', models.FloatField(default=0, max_length=200, verbose_name='value')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'draft'), (2, 'published'), (3, 'paused'), (4, 'retired')], default=1, verbose_name='status')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'draft'), (2, 'ordered'), (3, 'completed')], default=1, verbose_name='status')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Customer', verbose_name='customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='name')),
                ('value', models.FloatField(default=0, max_length=200, verbose_name='value')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('brand', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Brand', verbose_name='brand')),
                ('category', models.ManyToManyField(blank=True, to='taxonomies.Category', verbose_name='category')),
                ('user_group', models.ManyToManyField(blank=True, to='taxonomies.TargetGroup', verbose_name='target group')),
            ],
        ),
        migrations.CreateModel(
            name='ProductManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(blank=True, max_length=200, verbose_name='queryset')),
                ('value', models.FloatField(default=0, max_length=200, verbose_name='value')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomies.Color', verbose_name='color')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Product', verbose_name='product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='product number')),
                ('stock', models.IntegerField(blank=True, default=0, null=True, verbose_name='stock')),
                ('gross', models.FloatField(blank=True, null=True, verbose_name='price gross')),
                ('tax', models.FloatField(blank=True, null=True, verbose_name='price tax')),
                ('net', models.FloatField(blank=True, null=True, verbose_name='price net')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'draft'), (2, 'published'), (3, 'paused'), (4, 'retired')], default=1, verbose_name='status')),
                ('value', models.FloatField(default=0, max_length=200, verbose_name='value')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('product_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_option', to='shop.ProductManager', verbose_name='product and color')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomies.Size', verbose_name='size')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, null=True, verbose_name='quantity')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Customer', verbose_name='customer')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.Order', verbose_name='order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Product', verbose_name='product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('baseproductimage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.BaseProductImage')),
                ('image', models.ImageField(blank=True, upload_to=shop.models.media.create_product_image_path, verbose_name='image')),
                ('product_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image', to='shop.ProductManager', verbose_name='product')),
            ],
            bases=('shop.baseproductimage',),
        ),
        migrations.CreateModel(
            name='ProductBrandImage',
            fields=[
                ('baseproductimage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.BaseProductImage')),
                ('image', models.ImageField(blank=True, upload_to=shop.models.media.create_product_brand_image_path, verbose_name='image')),
                ('product_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_image', to='shop.ProductManager', verbose_name='product')),
            ],
            bases=('shop.baseproductimage',),
        ),
    ]
