# Generated by Django 3.0.8 on 2020-07-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('price', models.FloatField(null=True, verbose_name='price')),
                ('image', models.ImageField(upload_to='', verbose_name='image')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'draft'), (2, 'published'), (3, 'paused'), (4, 'retired')], default=1, null=True, verbose_name='status')),
            ],
        ),
    ]
