# Generated by Django 3.0.10 on 2020-10-10 11:16

from django.db import migrations, models
import django.db.models.deletion
import shop.models.functions.brand
import shop.models.media


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, verbose_name='order')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
            ],
        ),
        migrations.CreateModel(
            name='BasicApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_url', models.URLField(blank=True, verbose_name='home url')),
                ('key', models.CharField(blank=True, max_length=200, verbose_name='key')),
                ('secret', models.CharField(blank=True, max_length=200, verbose_name='secret')),
            ],
        ),
        migrations.CreateModel(
            name='BasicBanking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.CharField(blank=True, max_length=20, verbose_name='iban')),
                ('bic', models.CharField(blank=True, max_length=20, verbose_name='bic')),
            ],
        ),
        migrations.CreateModel(
            name='BasicImprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='company name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phone', models.CharField(max_length=200, unique=True, verbose_name='phone number')),
                ('line_1', models.CharField(max_length=200, verbose_name='line 1')),
                ('line_2', models.CharField(blank=True, max_length=200, verbose_name='line 2')),
                ('post_code', models.IntegerField(verbose_name='post code')),
                ('city', models.CharField(max_length=200, verbose_name='city')),
                ('tax_number', models.CharField(max_length=200, unique=True, verbose_name='tax number')),
            ],
        ),
        migrations.CreateModel(
            name='BasicMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('value', models.FloatField(default=0, max_length=200, verbose_name='value')),
            ],
            options={
                'verbose_name': 'meta data',
                'verbose_name_plural': 'meta data',
            },
        ),
        migrations.CreateModel(
            name='BasicPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder', models.BooleanField(blank=True, verbose_name='account holder')),
                ('firstname', models.CharField(blank=True, max_length=200, verbose_name='firstname')),
                ('lastname', models.CharField(blank=True, max_length=200, verbose_name='lastname')),
            ],
        ),
        migrations.CreateModel(
            name='BasicStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('from_datetime', models.DateTimeField(blank=True, null=True, verbose_name='status from')),
                ('until_datetime', models.DateTimeField(blank=True, null=True, verbose_name='status until')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'draft'), (2, 'live'), (3, 'paused'), (4, 'retired')], default=1, verbose_name='status')),
            ],
        ),
        migrations.CreateModel(
            name='BasicTax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('included', models.BooleanField(blank=True, verbose_name='included')),
            ],
        ),
        migrations.CreateModel(
            name='BasicTaxZones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(blank=True, verbose_name='rate (in %)')),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BrandBranding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='name')),
                ('logo', models.ImageField(blank=True, upload_to=shop.models.functions.brand.brand_branding_upload_path, verbose_name='logo')),
            ],
        ),
        migrations.CreateModel(
            name='BrandSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backorders', models.BooleanField(default=False, verbose_name='backorders')),
                ('free_shipping_from', models.FloatField(blank=True, null=True, verbose_name='free shipping from')),
                ('return_policy_period', models.IntegerField(blank=True, null=True, verbose_name='return policy period')),
                ('return_shipping_costs', models.BooleanField(default=True, verbose_name='return shipping costs')),
            ],
            options={
                'verbose_name_plural': 'brand settings',
            },
        ),
        migrations.CreateModel(
            name='BrandSettingsSales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='amount (in %)')),
                ('from_datetime', models.DateTimeField(blank=True, null=True, verbose_name='status from')),
                ('until_datetime', models.DateTimeField(blank=True, null=True, verbose_name='status until')),
            ],
            options={
                'verbose_name_plural': 'brand settings sales',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'draft'), (2, 'ordered'), (3, 'completed')], default=1, verbose_name='status')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, null=True, verbose_name='quantity')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='ProductManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('query', models.CharField(blank=True, max_length=200, verbose_name='queryset')),
                ('value', models.FloatField(default=0, max_length=200, verbose_name='value')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='price (gross)')),
                ('product_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='product number')),
            ],
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
            ],
        ),
        migrations.CreateModel(
            name='BrandImprint',
            fields=[
                ('basicimprint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.BasicImprint')),
            ],
            bases=('shop.basicimprint',),
        ),
        migrations.CreateModel(
            name='BrandSettingsStatus',
            fields=[
                ('basicstatus_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.BasicStatus')),
            ],
            options={
                'verbose_name_plural': 'brand settings status',
            },
            bases=('shop.basicstatus',),
        ),
        migrations.CreateModel(
            name='ProductBrandImage',
            fields=[
                ('baseproductimage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.BaseProductImage')),
                ('image', models.ImageField(blank=True, upload_to=shop.models.media.create_product_brand_image_path, verbose_name='image')),
            ],
            bases=('shop.baseproductimage',),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('baseproductimage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.BaseProductImage')),
                ('image', models.ImageField(blank=True, upload_to=shop.models.media.create_product_image_path, verbose_name='image')),
            ],
            bases=('shop.baseproductimage',),
        ),
        migrations.CreateModel(
            name='ProductManagerStatus',
            fields=[
                ('basicstatus_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.BasicStatus')),
            ],
            bases=('shop.basicstatus',),
        ),
        migrations.CreateModel(
            name='ProductOptionStatus',
            fields=[
                ('basicstatus_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.BasicStatus')),
            ],
            bases=('shop.basicstatus',),
        ),
        migrations.CreateModel(
            name='ProductStatus',
            fields=[
                ('basicstatus_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.BasicStatus')),
            ],
            bases=('shop.basicstatus',),
        ),
    ]
