# Generated by Django 3.0.9 on 2020-08-30 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200829_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvaluelog',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='productbrandimage',
            name='product_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_image', to='shop.ProductManager', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image', to='shop.ProductManager', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='product_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_option', to='shop.ProductManager', verbose_name='product and color'),
        ),
    ]
