# Generated by Django 3.0.8 on 2020-07-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200728_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='language',
        ),
        migrations.RemoveField(
            model_name='product',
            name='style',
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=1, verbose_name='price'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'draft'), (2, 'published'), (3, 'paused'), (4, 'retired')], default=1, verbose_name='status'),
        ),
    ]
