# Generated by Django 3.0.10 on 2020-10-10 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201010_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandsettingssales',
            name='brand_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='shop.BrandSettings', verbose_name='brand settings'),
        ),
    ]
