# Generated by Django 3.0.10 on 2020-10-03 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomies', '0001_initial'),
        ('shop', '0002_auto_20201003_1109'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaxZones',
            new_name='BasicTaxZones',
        ),
    ]
