# Generated by Django 3.0.10 on 2020-10-03 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20201003_1152'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BrandSalesSettings',
            new_name='BrandSettingsSales',
        ),
        migrations.AlterField(
            model_name='brandperson',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='people', to='shop.Brand', verbose_name='brand'),
        ),
    ]
