# Generated by Django 3.0.10 on 2020-10-10 19:57

from django.db import migrations, models
import shop.models.functions.brand


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20201010_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandimprint',
            name='basicimprint_ptr',
        ),
        migrations.RemoveField(
            model_name='brandimprint',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='brandsettings',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='brandsettingssales',
            name='brand_settings',
        ),
        migrations.RemoveField(
            model_name='brandsettingsstatus',
            name='basicstatus_ptr',
        ),
        migrations.RemoveField(
            model_name='brandsettingsstatus',
            name='brand_settings',
        ),
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, upload_to=shop.models.functions.brand.brand_branding_upload_path, verbose_name='logo'),
        ),
        migrations.AddField(
            model_name='brand',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='name'),
        ),
        migrations.DeleteModel(
            name='BrandBranding',
        ),
        migrations.DeleteModel(
            name='BrandImprint',
        ),
        migrations.DeleteModel(
            name='BrandSettings',
        ),
        migrations.DeleteModel(
            name='BrandSettingsSales',
        ),
        migrations.DeleteModel(
            name='BrandSettingsStatus',
        ),
    ]
