# Generated by Django 3.0.10 on 2020-09-11 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('shop', '0004_remove_orderitem_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('product_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.ProductManager', verbose_name='product manager')),
                ('product_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.ProductOption', verbose_name='product option')),
                ('wcustomer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wcustomer', to='users.Customer', verbose_name='customer')),
            ],
        ),
    ]
