# Generated by Django 3.0.10 on 2020-10-03 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20201003_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='api',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shop.BasicApi', verbose_name='api'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='banking',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shop.BasicBanking', verbose_name='banking'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='branding',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shop.BrandBranding', verbose_name='branding'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='imprint',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shop.BasicImprint', verbose_name='imprint'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='meta_data',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shop.BasicMetaData', verbose_name='meta data'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='settings',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shop.BrandSettings', verbose_name='settings'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='tax',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shop.BasicTax', verbose_name='tax'),
        ),
    ]
