# Generated by Django 3.0.10 on 2020-09-11 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_wishlistitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlistitem',
            old_name='wcustomer',
            new_name='customer',
        ),
    ]
