# Generated by Django 3.0.10 on 2020-10-03 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20201003_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandperson',
            name='basicperson_ptr',
        ),
        migrations.RemoveField(
            model_name='brandperson',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='brandsettingssales',
            name='brand_settings',
        ),
        migrations.RemoveField(
            model_name='brandsettingsstatus',
            name='basicstatus_ptr',
        ),
        migrations.RemoveField(
            model_name='brandsettingsstatus',
            name='brand_settings',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='api',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='banking',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='branding',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='meta_data',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='settings',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='tax',
        ),
        migrations.DeleteModel(
            name='BrandBranding',
        ),
        migrations.DeleteModel(
            name='BrandPerson',
        ),
        migrations.DeleteModel(
            name='BrandSettings',
        ),
        migrations.DeleteModel(
            name='BrandSettingsSales',
        ),
        migrations.DeleteModel(
            name='BrandSettingsStatus',
        ),
    ]
