# Generated by Django 3.0.10 on 2020-09-09 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200909_1221'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserGroup',
            new_name='TargetGroup',
        ),
    ]
