# Generated by Django 3.0.10 on 2020-10-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20201010_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='name',
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='brand name'),
        ),
    ]
