# Generated by Django 3.0.10 on 2020-09-09 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxonomies', '0001_initial'),
        ('shop', '0006_auto_20200909_1226'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='color',
            name='basetaxonomy_ptr',
        ),
        migrations.RemoveField(
            model_name='country',
            name='basetaxonomy_ptr',
        ),
        migrations.RemoveField(
            model_name='size',
            name='basetaxonomy_ptr',
        ),
        migrations.RemoveField(
            model_name='targetgroup',
            name='basetaxonomy_ptr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='query',
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, to='taxonomies.Category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='user_group',
            field=models.ManyToManyField(blank=True, to='taxonomies.TargetGroup', verbose_name='target group'),
        ),
        migrations.AlterField(
            model_name='productmanager',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomies.Color', verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomies.Size', verbose_name='size'),
        ),
        migrations.AlterField(
            model_name='taxonomyvaluelog',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taxonomies.Category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='taxonomyvaluelog',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taxonomies.Color', verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='taxonomyvaluelog',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taxonomies.Size', verbose_name='size'),
        ),
        migrations.DeleteModel(
            name='BaseTaxonomy',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.DeleteModel(
            name='TargetGroup',
        ),
    ]
