# Generated by Django 3.0.10 on 2020-10-12 14:03

from django.db import migrations, models
import shop.models.functions.brand


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20201010_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='brand name'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=shop.models.functions.brand.brand_branding_upload_path, verbose_name='logo'),
        ),
    ]
