# Generated by Django 3.0.8 on 2020-08-20 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200808_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=200, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(blank=True, max_length=200, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='customer',
            name='line_1',
            field=models.CharField(blank=True, max_length=200, verbose_name='line 1'),
        ),
        migrations.AddField(
            model_name='customer',
            name='line_2',
            field=models.CharField(blank=True, max_length=200, verbose_name='line 2'),
        ),
        migrations.AddField(
            model_name='customer',
            name='zip',
            field=models.CharField(blank=True, max_length=200, verbose_name='postal code'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Customer', verbose_name='customer'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Order', verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Product', verbose_name='product'),
        ),
    ]
