# Generated by Django 3.0.10 on 2020-10-03 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomies', '0001_initial'),
        ('shop', '0006_auto_20201003_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicimprint',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomies.Country', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='basicimprint',
            name='company_name',
            field=models.CharField(max_length=200, verbose_name='company name'),
        ),
        migrations.AlterField(
            model_name='basicimprint',
            name='company_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomies.CompanyType', verbose_name='company type'),
        ),
        migrations.AlterField(
            model_name='basicimprint',
            name='line_1',
            field=models.CharField(max_length=200, verbose_name='line 1'),
        ),
        migrations.AlterField(
            model_name='basicimprint',
            name='line_2',
            field=models.CharField(max_length=200, verbose_name='line 2'),
        ),
        migrations.AlterField(
            model_name='basicimprint',
            name='phone',
            field=models.CharField(max_length=200, unique=True, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='basicimprint',
            name='post_code',
            field=models.IntegerField(verbose_name='post code'),
        ),
        migrations.AlterField(
            model_name='basicimprint',
            name='tax_number',
            field=models.CharField(max_length=200, unique=True, verbose_name='tax number'),
        ),
    ]
