# Generated by Django 3.0.10 on 2020-10-03 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomies', '0001_initial'),
        ('shop', '0007_auto_20201003_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicimprint',
            name='company_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='taxonomies.CompanyType', verbose_name='company type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basicimprint',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='taxonomies.Country', verbose_name='country'),
            preserve_default=False,
        ),
    ]
