# Generated by Django 3.0.10 on 2020-09-12 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('shop', '0007_auto_20200912_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='icustomer', to='users.Customer', verbose_name='customer'),
        ),
    ]
