# Generated by Django 3.0.10 on 2020-10-12 17:57

from django.db import migrations, models
import django.db.models.deletion
import shop.models.functions.brand


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20201012_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='brand_name',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='logo',
        ),
        migrations.AlterField(
            model_name='basicimprint',
            name='tax_number',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name='tax number'),
        ),
        migrations.CreateModel(
            name='BrandBranding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='brand name')),
                ('logo', models.ImageField(blank=True, null=True, unique=True, upload_to=shop.models.functions.brand.brand_branding_upload_path, verbose_name='logo')),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='shop.Brand', verbose_name='brand')),
            ],
        ),
    ]
