# Generated by Django 3.0.10 on 2020-09-12 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_orderitem_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product_manager',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_item', to='shop.ProductOption', verbose_name='product'),
        ),
    ]
