# Generated by Django 3.0.10 on 2020-10-03 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20201003_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandimprint',
            name='brand',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='imprint', to='shop.Brand', verbose_name='brand'),
        ),
    ]
