# Generated by Django 3.0.10 on 2020-10-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20201003_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicimprint',
            name='city',
            field=models.CharField(default=1, max_length=200, verbose_name='city'),
            preserve_default=False,
        ),
    ]
