# Generated by Django 3.0.10 on 2020-09-16 04:57

from django.db import migrations, models
import shop.models.media


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20200916_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbrandimage',
            name='image',
            field=models.ImageField(blank=True, upload_to=shop.models.media.create_product_brand_image_path, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, upload_to=shop.models.media.create_product_image_path, verbose_name='image'),
        ),
    ]
