# Generated by Django 3.0.10 on 2020-10-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20201003_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicimprint',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='basicimprint',
            name='phone',
            field=models.CharField(max_length=200, unique=True, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='basicimprint',
            name='tax_number',
            field=models.CharField(max_length=200, unique=True, verbose_name='tax number'),
        ),
    ]
