# Generated by Django 3.0.10 on 2020-10-07 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20201003_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadatacountry',
            name='basicmetadata_ptr',
        ),
        migrations.RemoveField(
            model_name='metadatacountry',
            name='taxonomy',
        ),
        migrations.RemoveField(
            model_name='metadatacurrency',
            name='basicmetadata_ptr',
        ),
        migrations.RemoveField(
            model_name='metadatacurrency',
            name='taxonomy',
        ),
        migrations.DeleteModel(
            name='MetaDataCompanyType',
        ),
        migrations.DeleteModel(
            name='MetaDataCountry',
        ),
        migrations.DeleteModel(
            name='MetaDataCurrency',
        ),
    ]
