# Generated by Django 3.0.8 on 2020-08-24 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20200824_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.PositiveSmallIntegerField(choices=[(1, 'click'), (2, 'wishlist'), (3, 'cart'), (4, 'order')], default=1, verbose_name='action')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Product', verbose_name='product')),
            ],
        ),
    ]
