# Generated by Django 3.0.10 on 2020-10-08 08:15

from django.db import migrations, models
import django.db.models.deletion
import shop.models.functions.brand


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20201007_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandBranding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='name')),
                ('logo', models.ImageField(blank=True, upload_to=shop.models.functions.brand.brand_branding_upload_path, verbose_name='logo')),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='shop.Brand', verbose_name='brand')),
            ],
        ),
    ]
