# Generated by Django 3.0.8 on 2020-08-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_productlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='value',
            field=models.FloatField(default=0, max_length=200, verbose_name='value'),
        ),
    ]
