# Generated by Django 3.0.10 on 2020-10-08 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_brandbranding'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backorders', models.BooleanField(blank=True, default=False, verbose_name='backorders')),
                ('free_shipping_from', models.FloatField(blank=True, verbose_name='free shipping from')),
                ('return_policy_period', models.IntegerField(blank=True, verbose_name='return policy period')),
                ('return_shipping_costs', models.BooleanField(blank=True, default=True, verbose_name='return shipping costs')),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='shop.Brand', verbose_name='brand')),
            ],
        ),
        migrations.CreateModel(
            name='BrandSettingsStatus',
            fields=[
                ('basicstatus_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.BasicStatus')),
                ('brand_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='shop.BrandSettings', verbose_name='brand settings')),
            ],
            bases=('shop.basicstatus',),
        ),
        migrations.CreateModel(
            name='BrandSettingsSales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, verbose_name='amount (in %)')),
                ('from_datetime', models.DateTimeField(blank=True, verbose_name='status from')),
                ('until_datetime', models.DateTimeField(blank=True, verbose_name='status until')),
                ('brand_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='shop.BrandSettings', verbose_name='brand settings')),
            ],
        ),
    ]
