# Generated by Django 3.0.8 on 2020-08-25 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_product_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValueLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.PositiveSmallIntegerField(choices=[(1, 'click'), (2, 'wishlist'), (3, 'cart'), (4, 'order')], default=1, verbose_name='action')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='value',
            field=models.FloatField(default=0, max_length=200, verbose_name='value'),
        ),
        migrations.AddField(
            model_name='category',
            name='value',
            field=models.FloatField(default=0, max_length=200, verbose_name='value'),
        ),
        migrations.DeleteModel(
            name='ProductLog',
        ),
        migrations.AddField(
            model_name='valuelog',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Brand', verbose_name='brand'),
        ),
        migrations.AddField(
            model_name='valuelog',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Category', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='valuelog',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Product', verbose_name='product'),
        ),
    ]
