# Generated by Django 3.0.9 on 2020-08-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='query',
            field=models.CharField(blank=True, max_length=200, verbose_name='queryset'),
        ),
    ]
