# Generated by Django 3.0.9 on 2020-08-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_product_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(1, 'women'), (1, 'men')], default=1, verbose_name='gender'),
        ),
    ]
