# Generated by Django 3.0.9 on 2020-08-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_product_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(1, 'unisex'), (2, 'women'), (3, 'men')], default=1, verbose_name='gender'),
        ),
    ]
