# Generated by Django 3.0.9 on 2020-08-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20200828_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='basetaxonomy',
            name='value',
            field=models.FloatField(default=0, max_length=200, verbose_name='value'),
        ),
    ]
