# Generated by Django 3.0.9 on 2020-08-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_basetaxonomy_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='hex',
            field=models.CharField(max_length=6, null=True, verbose_name='hex'),
        ),
    ]
